### ISSUE TITLE
Ensurepip missing from extension

### ISSUE THREAD

**Issue by thdeltei** [Azure/azure-python-siteextensions#1]
`ensurepip` seems to be missing from the extensions which limits the way we can use the python extensions to create virtual environments (it fails). I was wondering what is the reason behind this? Or am I missing something?

Thanks

**Comment by zooba** [comment]
You shouldn't create virtual environments using these. Azure App Service only supports one environment anyway, so just use `<path to python.exe> -m pip install ...` without bothering about a virtual environment.

(Note that the generated `pip.exe` files use absolute paths that will be incorrect, so you should use the `-m pip` style.)
