### ISSUE TITLE
ImportError: No module named 'tkinter'

### ISSUE THREAD

**Issue by ariellapinin** [Azure/azure-python-siteextensions#13]
After install python in azure functions app
nuget.exe install -Source https://www.siteextensions.net/api/v3/ -OutputDirectory D:\home\site\tools python352x64  
I run code with from "tkinter import *" get error 
ImportError: No module named 'tkinter'

**Comment by zooba** [comment]
Correct. tkinter is not available as its primary use is for windowing, which does not make sense on our services.

What are you trying to achieve that you need tkinter?

**Comment by baterja** [comment]
I need it too for creating plots with matplotlib which will be then saved and used later. Is there any alternative way to get this module?

**Comment by zooba** [comment]
If you change the matplotlib backend (`matplotlib.use("agg")`, if I remember correctly) then you shouldn't need tkinter to create and save plots.

Alternatively, if you do a regular install of Python on your own machine, you can copy the Tcl/Tk related files out of that and deploy them manually.
