### ISSUE TITLE
Path to Python is incorrect in docs

### ISSUE THREAD

**Issue by benc-uk** [Azure/azure-python-siteextensions#15]
The documentation refers to the installed path as `D:\home\python35\` however the path now includes the minor version and arch eg. `D:\home\python354x64\`

**Comment by zooba** [comment]
Which documentation are you referring to?

**Comment by benc-uk** [comment]
Sorry, I meant the **readme.md**

**Comment by zooba** [comment]
Ah, thanks. The instructions already said that you need to update the path based on the actual extension you are using, and the version used in the example is indeed at the path shown (and always will be), but the command line for building needed updating anyway so I did it.
