### ISSUE TITLE
[Errno 28] No space left on device installing dependencies with pip on Isolated I1 instances

### ISSUE THREAD

**Issue by twschiller** [Azure/azure-python-siteextensions#16]
Installing pip dependencies from a requirements file on Isolated I1 instances results results in "OSError: [Errno 28] No space left on device". Have to run the installation multiple times to install all dependencies. 

KUDU is reporting plenty of free space in D:\home and d:\local. Maybe hitting a quota issue on D:\local\temp?

D:\home usage: 256,000 MB total; 253,109 MB free
d:\local usage: 500 MB total; 483 MB free

I'm using the Python 361x64 extension deployed via ARM template. I don't recall hitting this error on Standard S1 instances.

> Exception:
> Traceback (most recent call last):
>   File "D:\Repos\azure-python-siteextensions\source_packages\python.3.6.1\tools\Lib\site-packages\pip\basecommand.py", line 215, in main
>   File "D:\Repos\azure-python-siteextensions\source_packages\python.3.6.1\tools\Lib\site-packages\pip\commands\install.py", line 324, in run
>   File "D:\Repos\azure-python-siteextensions\source_packages\python.3.6.1\tools\Lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
>   File "D:\Repos\azure-python-siteextensions\source_packages\python.3.6.1\tools\Lib\site-packages\pip\req\req_set.py", line 620, in _prepare_file
>   File "D:\Repos\azure-python-siteextensions\source_packages\python.3.6.1\tools\Lib\site-packages\pip\download.py", line 821, in unpack_url
>   File "D:\Repos\azure-python-siteextensions\source_packages\python.3.6.1\tools\Lib\site-packages\pip\download.py", line 663, in unpack_http_url
>   File "D:\Repos\azure-python-siteextensions\source_packages\python.3.6.1\tools\Lib\site-packages\pip\utils\__init__.py", line 599, in unpack_file
>   File "D:\Repos\azure-python-siteextensions\source_packages\python.3.6.1\tools\Lib\site-packages\pip\utils\__init__.py", line 499, in unzip_file
> OSError: [Errno 28] No space left on device: 'D:\\local\\Temp\\pip-build-gznapubw\\azure-batch\\azure/batch/models/recent_job.py'

**Comment by twschiller** [comment]
Might be provisioning problem. Looks like the Isolated I1 quota should be "very high" [1]. I will follow up with Azure support

> For Free, Shared and Consumption (Functions) sites, there is a 500MB limit for all these locations together (i.e. not per-folder). For Standard and Basic sites, the limit is very high (over 100GB).

[1] https://github.com/projectkudu/kudu/wiki/Understanding-the-Azure-App-Service-file-system#temporary-files

**Comment by zooba** [comment]
Doesn't look like anything for me to do here (though I did just update the packages to take up less space once installed), so closing this. Hopefully it's resolved on their side.

**Comment by twschiller** [comment]
Yes, this was a provisioning problem. Zero instances were being provisioned for our application (which we resolved with Azure support)
