### ISSUE TITLE
How in the hell do I actually use this?

### ISSUE THREAD

**Issue by 1337SEnergy** [Azure/azure-python-siteextensions#4]
I'll try to make this as brief as possible

1. azure is praised as some god-like service at our school, so I decided to give it a try
2. I want to run python Web Job in a Web App, however azure uses python 2.7.8, but I need any version above that for my code to work (SSL3 errors)
3. I'm using 2.7.12 on my local computer and everything works fine
4. I have no idea what I'm doing whenever I do anything on portal.azure.com

how do I update the python on my web app to 2.7.12 using THIS?

**Comment by prashanthmadi** [comment]
Below link would help you with it
https://prmadi.com/running-python-webjob-on-azure-app-services-using-non-default-python-version/
