### ISSUE TITLE
360x86 is failing to install

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-python-siteextensions#5]
@zooba Both with the Portal and Kudu

Failed to install web app extension Python 3.6.0 x86. {\"Message\":\"ExitCode: 4, Output: D:\\\\home\\\\SiteExtensions\\\\python360x86>taskkill /F /IM python.exe \\r\\n\\r\\nD:\\\\home\\\\SiteExtensions\\\\python360x86>if exist D:\\\\home\\\\Python35 rmdir /Q /S D:\\\\home\\\\Python35 \\r\\n\\r\\nD:\\\\home\\\\SiteExtensions\\\\python360x86>xcopy /s Python35 D:\\\\home\\\\Python35\\\\ \\r\\n0 File(s) copied, Error: Access is denied.\\r\\nFile not found - Python35, Kudu.Core.Infrastructure.CommandLineException: Access is denied.\\r\\nFile not found - Python35\\r\\nD:\\\\home\\\\SiteExtensions\\\\python360x86\\\\install.cmd \\r\\n   at Kudu.Core.Infrastructure.Executable.ExecuteInternal(ITracer tracer, Func`2 onWriteOutput, Func`2 onWriteError, Encoding encoding, String arguments, Object[] args)\\r\\n   at Kudu.Core.Infrastructure.Executable.ExecuteWithProgressWriter(ILogger logger, ITracer tracer, String arguments, Object[] args)\\r\\n   at Kudu.Core.SiteExtensions.SiteExtensionManager.<>c__DisplayClass25_1.<InstallExtension>b__1()\\r\\n   at Kudu.Core.Infrastructure.OperationManager.<>c__DisplayClass2_0.<Attempt>b__0()\\r\\n   at Kudu.Core.Infrastructure.OperationManager.Attempt[T](Func`1 action, Int32 retries, Int32 delayBeforeRetry, Func`2 shouldRetry)\\r\\n   at Kudu.Core.Infrastructure.OperationManager.Attempt(Action action, Int32 retries, Int32 delayBeforeRetry)\\r\\n   at Kudu.Core.SiteExtensions.SiteExtensionManager.<InstallExtension>d__25.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\\r\\n   at Kudu.Core.SiteExtensions.SiteExtensionManager.<TryInstallExtension>d__24.MoveNext()\"}

**Comment by zooba** [comment]
Should be fixed in the latest update

**Comment by huguesv** [comment]
No, still broken.

**Comment by zooba** [comment]
Ah, because I updated 3.6.1 but not 3.6.0. I'll do that

**Comment by zooba** [comment]
New packages have been uploaded
