### ISSUE TITLE
D:/home/Python35 is not created when installing 353x86

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-python-siteextensions#6]
@zooba But available under SiteExtensions.

I'm not sure it's on purpose, do we create d:/home/pythonXX only for x64?

**Comment by zooba** [comment]
Not sure whether this will still occur with the updated one. Feel free to close if that works

**Comment by zooba** [comment]
@lmazuel Actually, 3.5.3 is where I changed the package format to use a different directory. It will be installed under `D:\home\python353x86` or `D:\home\python353x64` (that is, same name as the package itself).

This should make it easier to predict what the path will be, and also make it safer to install updates.

**Comment by lixzhang** [comment]
@zooba The newly updated 3.5.3 and 3.5.2 are not working for the following command. Version 3.5.2.2 was working properly before it was updated to 3.5.2.4 a few hours ago.

python -m venv --without-pip env. 

The error is "No module named venv"

**Comment by zooba** [comment]
@lixzhang `venv` is deliberately excluded from these packages - just install packages directly into the main directory. (There's no sensible isolation within an app service container anyway, so a virtual environment is just wasting space.)

**Comment by lixzhang** [comment]
@zooba agree that virtual environment is not the best option for an app service container. we have some heritage code (in a batch script) that depends on  <code>venv</code> so it looks like we have to go back and rewrite it.

**Comment by lmazuel** [comment]
I close since as @zooba said it's under "'python353x86"
